name: Playwright — Staging

on:
  # push:
  #   branches: [ "staging" ]   # edit branch names as you use
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright tests against Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (staging)
        env:
         ENV: staging
         STAGING_URL: ${{ secrets.STAGING_URL }}
         STAGING_MOBILE_NUMBER: ${{ secrets.STAGING_MOBILE_NUMBER }}
         STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
          # API_KEY: ${{ secrets.STAGING_API_KEY }}

        run: npx playwright test

      - name: Check Allure Results
        run: ls -la allure-results

      - name: Install Allure CLI
        run: npm install -g allure-commandline
          
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-staging
          path: playwright-report
      
     # Upload Allure Report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-staging
          path: allure-report


    # ✅ Send email notification to Product Manager
      - name: Send email notification
        if: always()  
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Playwright CI - ${{ job.status }}"
          to: "tanha.tahity@vivasoftltd.com"
          from: "Financfy QA <${{ secrets.SMTP_USERNAME }}>"
          body: |
            Hello Team,

            The workflow has completed with status: ${{ job.status }}.

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run Number: ${{ github.run_number }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
